### PR TITLE
PE logging improvements

### PR DESCRIPTION
**Pull request by Archar123**
add more log

### CODE REVIEW

**Comment by Archar123** [comment]
add more middle log

**Comment by notpidgey** [comment]
Thanks for your PR, I will fully review it when I get the chance to.

**Comment by notpidgey** [comment]
I had a bit of a git issue and I ended up accidentally force pushing the repository. Could you potentially clone this repo again and make a new PR with the same changes? Sorry about this.

I'm pretty content with this change otherwise.

**Comment by notpidgey** [comment]
The disassembler is going to get reworked pretty soon but the graphviz for the code should stick after I finish that change

**Pull request closed without merging**
